/*
Compnay            : xxxxx
Name               : AccountTriggerHandlerHelper_Test
Description        : test calass for helper class for trigger account object
Created By Name    : Shatrughna Salunke
Careated Date      : 7,Jan 2021 
Last Modified  By  : Shatrughna Salunke
Last Modified Date : 7,Jan,2021
User Story Number  :  
*/
public with sharing class AccountTriggerHandlerHelper_Test {
    public AccountTriggerHandlerHelper_Test() {

    }
}