/**
 * @description       : 
 * @author            : Shatrughna.Salunke
 * @group             : 
 * @last modified on  : 21-05-2021
 * @last modified by  : Shatrughna.Salunke
 * Modifications Log 
 * Ver   Date         Author               Modification
 * 1.0   21-05-2021   Shatrughna.Salunke   Initial Version
**/

public with sharing class PurgeContactBatch {

    public PurgeContactBatch()  {
    }
    public static String getData (String Name) {
         
        return null;
      }
}